require: rubocop-performance

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.2

Metrics/AbcSize:
  Max: 65

Metrics/BlockLength:
  Max: 60

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Max: 500

Metrics/PerceivedComplexity:
  Max: 25

Rails/SkipsModelValidations:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

# we drop this, if we drop Rails 4.2 support
Rails/ApplicationRecord:
    Enabled: false

Performance/ChainArrayAllocation:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false
